### ISSUE TITLE
9/25 Sunday: OffMaptime - Mapping Event @ Leimert Park Monthly ArtWalk

### ISSUE THREAD

**Issue by machikoyasuda** [maptimeLA/maptimela-roadmap#12]
- ArtWalk: https://www.facebook.com/KaosNetwork/
- Contact: Kenneth Wyrick 
- Project: Set up an instance of Sahana Eden Humanitarian Management Platform for Leimert Park area

**Comment by cityhubla** [comment]
CCing @kmw to the this event planning

**Comment by kmw** [comment]
Great!  While Sahana Eden is the platform we want to include OSM mobile phone app to map the sidewalks, trees, alleys and facades based on the default view at: https://www.openstreetmap.org/#map=17/34.00602/-118.33279

**Comment by machikoyasuda** [comment]
@kmw  It is the 25th Sunday. Last Sunday of the month.  AfroGeek - I love that theme :)

<img width="699" alt="screenshot 2016-07-29 17 44 38" src="https://cloud.githubusercontent.com/assets/3673236/17266953/256ab6b8-55b4-11e6-821f-0df711a5a143.png">

**Comment by cityhubla** [comment]
@kmw, what tools are you suggesting to map with?
Here's what comes to mind
- [Field Papers](http://fieldpapers.org/) All paper, but we can upload to OSM by editing
- [maps.me](http://maps.me/en/home), this can tag POI places for iOS and Android
- [Vespucci](http://vespucci.io/) for Android, can edit POIs
- [Openmaps](http://ize.company/openmaps/) for iOS
