### ISSUE TITLE
Ideas from Planning Session 8.4.2016

### ISSUE THREAD

**Issue by cityhubla** [maptimeLA/maptimela-roadmap#14]
## Board 1

![image](https://cloud.githubusercontent.com/assets/6407796/17597502/ed1e3aea-5faa-11e6-9ec8-5cdf6f4ddc4c.png)
- Invite the modern hiker founder to a meeting
- co-working spaces
- Hiking trips
  - walking tours (urban)
  - mapillary
  - iNaturalist (animals/plants)
- Elevation profile map
- Record maptime presentation and post online
- Training on remote sensing in QGIS
- OSM Map Items
  - free parking (tag); street sweeping (tag)
  - public bathrooms
  - Pedestrian cut-throughs
  - Street art
  - Events spaces
- Themed maps for heritage months
  - Asian American, etc.
- Databases in QGIS
- Web Series: "How I made that map"
- Map of family hometowns: "Find your long lost cousin!"
  - Extend back to grandparents
- Map  of "little" international areas in Los Angeles
  - Filipinotown, Thai Town, Little India, Little Ethiopia, Mariachi Plaza
- Google Earth / Maps
  - Embed photos in KMZ popups
  - Google MyMaps
- MapTrivia Night
- "Watering holes for the soul" - Map of interesting spots in Los Angeles (like Angel City Brewery)
  - Combine w/ intro to web mapping
  - Everybody come w/ 3 favorite places
- Spatial Olympics
  - Trivia, Google Streetmap random view
- Maptime Craft Time!
  - Embroidered maps
- Put up a database and connect to a webmap
- Invite local map makers to give presentations
  - [Eric Brightwell](https://ericbrightwell.com/)
- Blocks and Lots Creater (Rosten Woo)
- Update Maptime Website

**Comment by cityhubla** [comment]
## Board 2

![image](https://cloud.githubusercontent.com/assets/6407796/17597621/80da6b28-5fab-11e6-8469-d89270292ebc.png)

**Comment by techlady** [comment]
I made a database of the LA City list of historic sites. It doesn't have latitude and longitude, but it does have addresses. It could be an interesting project. I also like a lot of the suggestions above. Another possibility is mapping LA "official" neighborhoods, such as the little signs you see around town giving names to neighborhoods. I think they have, sort-of official borders, I know the guy in charge of neighborhood councils, Steven Box.
