### ISSUE TITLE
Event: Women Who Code x MaptimeLA on the westside

### ISSUE THREAD

**Issue by machikoyasuda** [maptimeLA/maptimela-roadmap#3]
Event sponsor: At Philosophie, along the Expo Line
Event sponsor person: @wykhuh
Need: date / time
Outreach: UCLA, SMC groups

**Comment by machikoyasuda** [comment]
@wykhuh we're gonna start planning stuff here :)

**Comment by cityhubla** [comment]
@machikoyasuda @wykhuh, I'm game for the 20th or 27th for the event
