### ISSUE TITLE
Event: Mapillary and OSM camping trip to Catalina

### ISSUE THREAD

**Issue by machikoyasuda** [maptimeLA/maptimela-roadmap#5]

**Comment by jschleuss** [comment]
This is a possible weekend camping trip to Catalina Island. We'd add imagery to Mapillary and OpenStreetMap updates of businesses, addresses, benches, trees (and other notable plants in the gardens) and historic landmarks. 

Requirements:
- golf cart
- mobile phone
- camping equipment

**Comment by machikoyasuda** [comment]
I have:
- 1 tent
- 2 sleeping pads
- 2 sleeping bags
- 1 bike helmet (to attach camera to)
- 1 cell phone bike handlebar attachment
- Lots of camping cooking equipment (coffee, water, cooking)
